apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc
spec:
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: "{{ .Values.appPort }}"
      targetPort: "{{ .Values.containerPort }}"
